export default class ActionTypes {
    
    public static ADD_INGREDIENT = 'ADD_INGREDIENT';
    public static REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
    public static INIT_INGREDIENTS = 'INIT_INGREDIENTS';
    public static RESET_BURGER_BUILDER_STATE = 'RESET_BURGER_BUILDER_STATE';

    public static PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';

    public static FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
    public static FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

    public static LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    public static LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
    public static SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
    public static UPDATE_STATE_WITH_AUTH_INFO_ON_LOAD = 'UPDATE_STATE_WITH_AUTH_INFO_ON_LOAD';
    public static SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';
    public static CLEAR_REDIRECT_PATH = 'CLEAR_REDIRECT_PATH';
        
}